[package]
name = "chill"
version = "0.1.1+master"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Client-side CouchDB library"
repository = "https://github.com/chill-rs/chill"
documentation = "https://chill-rs.github.io/chill/doc/v0.1.1/chill/"
keywords = ["couchdb", "database", "nosql"]

[dependencies]
base64 = "0.1"
regex = "0.1"
serde = "0.7"
serde_json = "0.7"
tempdir = "0.3"
url = "1"

[dependencies.mime]
version = "0.2"
features = ["serde"]

[dependencies.hyper]
version = "0.9"
features = ["serde-serialization"]

[dependencies.uuid]
version = "0.1"
features = ["serde"]
